# configs/optimizer/adamw_scaled.yaml
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-4
  weight_decay: 1e-6
  
  # Toggle for fine-grained parameter grouping (Regex based)
  use_param_groups: false
  
  # Optional: Fine-grained control over parameter groups using regex
  # Groups are matched in order; first match wins.
  param_groups:
    - params: "backbone"
      lr: ${oc.eval:"${optimizer.optimizer.lr} / 10"}
      # lr: ${oc.eval:"${optimizer.lr} / 10"}
      # 1e-5 # ${optimizer.lr}
    - params: '^(?=.*encoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.0
    - params: '^(?=.*decoder(?=.*bias|.*norm.*weight)).*$'
      weight_decay: 0.0

scheduler:
  type: "reduce_lr_on_plateau"
  warmup_steps: 1000
  factor: 0.9
  patience: 5
  T_max: ${trainer.max_epochs}
  last_epoch: -1
  eta_min: 1e-6

training:
  profiler:
    type: 'simple'
