# @package model.backbone

type: "dinov2"
pretrained_name_or_path: "facebook/dinov2-base"
name: "dinov2-base"
model_name: "${extract_name:${.pretrained_name_or_path}}"
decoder_name: "swin-large"
training_mode: "frozen"  # frozen | lora | full_finetune
gradient_checkpointing: false
adapter_dim: 384
spm_dim: 32
interaction_indices: [2, 7, 11]
interaction_num_heads: 6
token_mlp_ratio: 0.5
spatial_mlp_ratio: 0.5
out_indices: [3, 6, 9, 12]
fpn_type: "fused"        # fused | tiny | simple | sfp
intermediate_resolutions: [168, 84, 42, 21]
