# configs/model/backbone/rtdetr_r101vd.yaml
# @package model.backbone

type: "resnet" 
name: "rtdetr_v2_r101vd" # Matches the supported model names
model_name: resnet101

# Freezing params
train_backbone: false     # If false, we freeze layers
freeze_at_stage: 0        # 0=Stem, 1=Layer1, ..., 4=Layer4 (Freeze everything)

# These are needed for logic consistency but won't change the architecture
# (The official R101 backbone outputs these channels naturally)
intermediate_channel_sizes: [512, 1024, 2048]