name: yolov5
input_size: 640

yolov5:
  # Must point to official YOLOv5 source tree.
  repo_path: ${hydra:runtime.cwd}/models/yolov5

  yolo_size: m
  # Official YOLOv5 model definition yaml (relative to repo_path or absolute path).
  model_cfg: models/yolov5${model.yolov5.yolo_size}.yaml
  # Optional pretrained checkpoint (.pt). Leave null for random init.
  # Use 'yolov5s', 'yolov5m', etc. to load from torch hub dynamically.
  # Use 'yolov5s.pt' etc. to load from local file.
  weights: /project/aip-robsc/asinha/cellanome/as-cells/yolov5${model.yolov5.yolo_size}.pt

  # YOLO inference/eval settings
  iou_threshold: 0.6 # 0.45
  cache_images: false

  # Native YOLO hyperparameters passed into dataloader/train behavior.
  hyp:
    lr0: 0.01
    lrf: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    warmup_bias_lr: 0.1
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    obj: 1.0
    obj_pw: 1.0
    iou_t: 0.6
    anchor_t: 4.0
    fl_gamma: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    degrees: 1.0
    translate: 1.0
    scale: 1.0
    shear: 0.0
    perspective: 0.0
    flipud: 1.0
    fliplr: 1.5
    mosaic: 0.0
    mixup: 1.0
    copy_paste: 1.0

  optimizer:
    type: sgd
    lr: 0.01
    momentum: 0.937
    weight_decay: 0.0005
    nesterov: true

  dataset_cache_dir: ${hydra:runtime.cwd}/.cache/datasets/yolov5_${data.train_name}_${data.val_name}_${data.test_name}

# --- General ---
label_map:
  0: "cell"
  1: "bead"
  2: "cell-adhered"
  3: "soma"

detection_threshold: 0.001
draw_threshold: 0.4
max_detections: 100

ema:
  enabled: true
  decay: 0.9999
  tau: 2000
  warmup_steps: 100

# /project/aip-robsc/asinha/cellanome/DATA/checkpoints/yolov5_2026-02-28_12_4176937_12-07/ckpts/yolov5-ema-epoch-19-val_map_ema-0.4979.ckpt
# /project/aip-robsc/asinha/cellanome/DATA/checkpoints/yolov5_2026-02-28_12_4176937_12-07/ckpts/yolov5-regular-epoch-15-val_map-0.4917.ckpt
