# configs/config.yaml
# Main config. This file selects the default for each config group.

defaults:
  - model: rtdetr_base
  - model/backbone: dinov2
  - optimizer: adamw_scaled
  - scheduler: cosine_warmup
  - trainer: default
  - checkpointing: default
  - logging: default
  - initialization: default
  - data: default
  - _self_  # Allows this file to add its own keys

# --- Top-Level Global Settings ---
seed: 42
# run_name: "rtdetr_dinov2_${now:%Y-%m-%d_%H-%M-%S}"
run_name: "rtdetrv2_${model.backbone.name}_${now:%Y-%m-%d}"
debug: false
test_only: false

# file/folder names to use 
val_name: ${data.val_name}
test_name: ${data.test_name}
train_name: ${data.train_name}

training:
  profiler:
    type: 'simple'