# configs/config.yaml
# Main config. This file selects the default for each config group.

defaults:
  - model: rtdetr_base
  - optimizer: adamw_scaled
  - scheduler: cosine_warmup
  - trainer: default
  - checkpointing: default
  - logging: default
  - initialization: default
  - data: default
  - _self_  # Allows this file to add its own keys

# --- Top-Level Global Settings ---
seed: 42
# run_name: "rtdetr_dinov2_${now:%Y-%m-%d_%H-%M-%S}"
run_name: "rtdetrv2_${model.backbone.name}_${now:%Y-%m-%d}"
debug: false

# allow remapping of labels
remap_labels: false
test_only: false

# file/folder names to use 
val_name: ${data.val_name}
test_name: ${data.test_name}
train_name: ${data.train_name}

# --- Label Remapping ---
# Merges multiple source classes into a single target class
#model:
#  label_map:
#    0: 'cell'
#    1: 'bead'

data:
  class_remapping:
    'cell-adhered': 'cell'
    'soma': 'cell'

training:
  profiler:
    type: 'simple'

inference:
  mode: dataset        # dataset | folder | single
  image_path: null     # for mode=single
  folder_path: null    # for mode=folder
  gt_json: _annotations.coco.json
  output_dir: predictions
  max_viz: -1          # -1 = save all, otherwise cap at this number
  sliding_window:
    overlap_x: 80
    overlap_y: 80
    nms_threshold: 0.15
