# ultralytics yolov5 config for validation
# original path to data
path: /project/aip-robsc/asinha/cellanome/as-cells/.cache/datasets/yolov5_train_valid_test/
train: images/train/
val: images/valid/
test: images/test/

# data path with no >300 bboxes during inference
# path: /project/aip-robsc/asinha/cellanome/as-cells/.cache/datasets/yolov5_train_valid_no300_test_no300/
train: images/train/
# val: images/valid_no300/
test: images/test/

nc: 4

names:
  0 : cell
  1 : bead
  2 : cell-adhered
  3: soma