# configs/logging/default.yaml
# Default logging settings (WandB)

wandb:
  enabled: true
  # project: "rt-detr-cell-detection"
  project: 'cell-detection'
  # 'name' will be set by the top-level 'run_name'
  tags: ["rt-detr", "cell-detection"]
  notes: "Training RT-DETR with DINOv2 backbone"
